#! /bin/sh

JARFILE="$(cd "$(dirname "$0")" && pwd -P)/outputjar"

if [ -n "$LOG4J_CONF" ]; then
  LOG4J_OPTS="-Dlog4j.configurationFile=file:${LOG4J_CONF}"
fi

if [ -n "$JDK_PATH" ]; then
  PATH="$JDK_PATH/bin:$PATH"
fi

JVM_OPTS="$LOG4J_OPTS -Dfile.encoding=UTF8 -Xms256m -Xmx1g -Dsun.net.client.defaultConnectTimeout=120000 -Dsun.net.client.defaultReadTimeout=120000 -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSParallelRemarkEnabled -XX:MaxGCPauseMillis=5 -XX:+OptimizeStringConcat -XX:+UseCompressedOops -XX:+AggressiveOpts -XX:MaxInlineSize=100 -Xloggc:/var/log/{{sanitized}}/gc.log -verbose:gc -XX:+PrintGCDetails -XX:ErrorFile=/var/log/{{sanitized}}/jvm-fatal%p.log -Dhttps.protocols=SSLv3 -agentlib:jdwp=transport=dt_socket,server=y,suspend=n"

if [ -f "$JARFILE" ]; then
  exec java ${JVM_OPTS} -jar "$JARFILE" server "$@"
else
  JVM_OPTS="${JVM_OPTS}" exec lein run server "$@"
fi
